# Generated by Django 3.2.15 on 2022-08-17 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(verbose_name='Табельный номер')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronimic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('birthplace', models.CharField(blank=True, max_length=50, null=True, verbose_name='Место рождения')),
                ('education_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Уровень образования')),
                ('education_institution', models.TextField(blank=True, null=True, verbose_name='Наименование образовательной организации')),
                ('qualification', models.CharField(blank=True, max_length=50, null=True, verbose_name='Квалификация')),
                ('specialty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Специальность')),
                ('diploma_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Серия и номер диплома')),
                ('graduation_year', models.DateField(blank=True, null=True, verbose_name='Год окончания')),
                ('profession', models.CharField(blank=True, max_length=50, null=True, verbose_name='Профессия')),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Семейное положение')),
                ('passport_series', models.IntegerField(blank=True, null=True, verbose_name='Серия паспорта')),
                ('passport_no', models.IntegerField(blank=True, null=True, verbose_name='Номер паспорта')),
                ('passport_issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('passport_issue_authority', models.TextField(blank=True, null=True, verbose_name='Кем выдано')),
                ('registration_address', models.TextField(blank=True, null=True, verbose_name='Адрес регистрации')),
                ('actual_adress', models.TextField(blank=True, null=True, verbose_name='Фактический адрес')),
                ('military_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория запаса')),
                ('military_rank', models.CharField(blank=True, max_length=100, null=True, verbose_name='Воинское звание')),
                ('military_profile', models.CharField(blank=True, max_length=100, null=True, verbose_name='Состав (профиль)')),
                ('military_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Полное кодовое обознчание ВУС')),
                ('fitness_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория годности к военной службе')),
                ('commissariat', models.TextField(blank=True, null=True, verbose_name='Наименование военного комиссариата по месту воинского учета')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Фамилия, имя, отчество')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Год рождения')),
                ('relation', models.CharField(max_length=100, verbose_name='Степень родства')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='regs.personnel', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Член семьи',
                'verbose_name_plural': 'Члены семьи',
            },
        ),
    ]
