# Generated by Django 3.2.15 on 2022-08-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regs', '0002_auto_20220817_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthyear',
            field=models.DateField(verbose_name='Год рождения'),
        ),
    ]
