# Generated by Django 3.2.15 on 2022-08-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regs', '0003_alter_member_birthyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthyear',
            field=models.DateField(blank=True, null=True, verbose_name='Год рождения'),
        ),
    ]
