# Generated by Django 3.2.15 on 2022-08-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regs', '0004_alter_member_birthyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthyear',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Год рождения'),
        ),
    ]
