# Generated by Django 3.2.15 on 2022-08-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regs', '0005_alter_member_birthyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
